### ISSUE TITLE
setMockMethodCallHandler was removed from MethodChannel after upgrading flutter to v2.5.2

### ISSUE THREAD

**Issue by anastaleb** [lsegal/flutter_multi_instance_handler#1]
I have upgraded Flutter recently and couldn't build after this upgrade due to the use of a method that was removed from MethodChannel which is setMockMethodCallHandler,
I don't think this is a big issue since method setMethodCallHandler is working fine after I temporarily replaced it in file controller.dart.
can you please upgrade this package to resolve this issue for everyone?

**Comment by lsegal** [comment]
Should be fixed by #2
